[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remapping = [
    "@openzeppelin/contracts/=/home/codezeros/Desktop/solidity/lib/openzeppelin-contracts/contracts/",
    "ds-test/=/home/codezeros/Desktop/solidity/lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=/home/codezeros/Desktop/solidity/lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=/home/codezeros/Desktop/solidity/lib/openzeppelin-contracts/lib/forge-std/src/",
    "openzeppelin-contracts/=/home/codezeros/Desktop/solidity/lib/openzeppelin-contracts/"
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options